-- ============================================
-- INSERT data from payload_vinhthanh.json
-- Generated automatically
-- ============================================

-- === WARD (unit) ===
INSERT INTO "ward" ("id", "parent_id", "name", "type") VALUES (248, NULL, 'VPĐT các phường thuộc huyện Vĩnh Thạnh (cũ)', 'unit');
INSERT INTO "ward" ("id", "parent_id", "name", "type") VALUES (276, 248, 'UBND Xã Vĩnh Thạnh - Tỉnh Gia Lai', 'unit');

-- === ORGANIZATIONAL (dept) ===
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (278, 276, 'Lãnh đạo UBND', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (280, 276, 'Văn phòng UBND và HĐND', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (283, 276, 'Trung tâm phục vụ Hành chính công', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (286, 276, 'Phòng Kinh tế - Xã Vĩnh Thạnh - Tỉnh Gia Lai', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (289, 276, 'Phòng Văn hóa - Xã hội', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (1271, 276, 'Quản trị hệ thống', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (7704, 276, 'Trung tâm Văn hóa - Thông tin - Thể thao xã Vĩnh Thạnh', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (7778, 276, 'Ban Quản lý công ích xã Vĩnh Thạnh', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (37589, 276, 'Hội đồng nhân dân xã', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (38056, 276, 'Ban chỉ huy quân sự', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (71446, 276, 'Công an xã', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (242929, 276, 'Trường Mầm Non Vĩnh Thạnh', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (243641, 276, 'Trường Mầm Non Vĩnh Hảo', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (244484, 276, 'Trường tiểu học Vĩnh Thạnh', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (244489, 276, 'Trường tiểu học Vĩnh Hảo', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (244494, 276, 'Trường THCS Vĩnh Thạnh', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (244521, 276, 'Trường THCS Vĩnh Hảo', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (1564185, 276, 'Ủy ban bầu cử', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (1920094, 276, 'Trạm y tế', 'dept');
INSERT INTO "organizational" ("id", "parent_id", "name", "type") VALUES (4006937, 276, 'Cụm thi đua khen thưởng', 'dept');

-- === PERSON (alias) ===
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (279, 278, 'Chủ tịch UBND', 'thonglm@vinhthanh.gialai.gov.vn', 'Lê Minh Thông', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (284, 283, 'Văn thư', 'vanthuhcc@vinhthanh.gialai.gov.vn', 'Văn thư Trung tâm phục vụ Hành chính công', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (287, 286, 'Văn thư', 'vanthukt@vinhthanh.gialai.gov.vn', 'Văn thư phòng Kinh tế', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (290, 289, 'Văn thư', 'vanthuvhxh@vinhthanh.gialai.gov.vn', 'Văn thư phòng Văn hóa - Xã hội', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (375, 278, 'Phó Chủ tịch UBND', 'truongnq@vinhthanh.gialai.gov.vn', 'Nguyễn Quốc Trường', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (376, 278, 'Phó Chủ tịch UBND', 'luantb@vinhthanh.gialai.gov.vn', 'Trịnh Bảo Luân', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (385, 280, 'Chuyên viên', 'anhlk@vinhthanh.gialai.gov.vn', 'Lê Kim Anh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (386, 280, 'Chuyên viên', 'phonglm@vinhthanh.gialai.gov.vn', 'Lê Minh Phong', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (387, 280, 'Chuyên viên', 'nhicth@vinhthanh.gialai.gov.vn', 'Cao Thị Hoài Nhị', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (388, 280, 'Chánh Văn phòng', 'duyvt@vinhthanh.gialai.gov.vn', 'Võ Trọng Duy', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (397, 286, 'Phó Trưởng phòng', 'lentn@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Ngọc Lê', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (398, 286, 'Chuyên viên', 'tamlt@vinhthanh.gialai.gov.vn', 'Lê Thanh Tâm', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (399, 286, 'Chuyên viên', 'nguyetnth@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Hồng Nguyệt', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (400, 286, 'Chuyên viên', 'lenhmt@vinhthanh.gialai.gov.vn', 'Mang Thành Lệnh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (402, 286, 'Chuyên viên', 'bacph@vinhthanh.gialai.gov.vn', 'Phạm Huy Bắc', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (410, 289, 'Trưởng phòng', 'lapdh@vinhthanh.gialai.gov.vn', 'Đặng Hữu Lập', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (414, 289, 'Chuyên viên', 'hoalt@vinhthanh.gialai.gov.vn', 'Lê Thị Hòa', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (415, 289, 'Chuyên viên', 'chault@vinhthanh.gialai.gov.vn', 'Lê Thị Châu', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (416, 289, 'Chuyên viên', 'thanht@vinhthanh.gialai.gov.vn', 'Huỳnh Thị Thân', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (423, 286, 'Trưởng phòng Kinh tế', 'trinhnt@vinhthanh.gialai.gov.vn', 'Nguyễn Tuấn Trình', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (424, 283, 'Chuyên viên', 'hattt@vinhthanh.gialai.gov.vn', 'Trần Thị Thu Hà', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (425, 283, 'Chuyên viên', 'kietta@vinhthanh.gialai.gov.vn', 'Tô Anh Kiệt', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (427, 289, 'Chuyên viên', 'congnc@vinhthanh.gialai.gov.vn', 'Nguyễn Chí Công', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (428, 283, 'Chuyên viên', 'trinhtdv@vinhthanh.gialai.gov.vn', 'Trương Đoàn Việt Trinh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1272, 1271, 'Quản trị đơn vị', 'admin@vinhthanh.gialai.gov.vn', 'Quản Trị Đơn Vị', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1901, 286, 'Chuyên viên', 'oanhdtk@vinhthanh.gialai.gov.vn', 'Đặng Thị Kim Oanh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (7779, 7778, 'Văn Thư Ban Quản Lý', 'vanthubql@vinhthanh.gialai.gov.vn', 'Văn Thư Ban Quản lý', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8408, 7704, 'Phó giám đốc', 'binhnv@vinhthanh.gialai.gov.vn', 'Nguyễn Văn Bình', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8412, 7704, 'chuyên viên', 'lientlt@vinhthanh.gialai.gov.vn', 'Trần Lương Thị Liên', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8414, 7704, 'chuyên viên', 'anhttn@vinhthanh.gialai.gov.vn', 'Trần Thị Ngọc Ánh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8416, 7704, 'Chuyên viên', 'vutn@vinhthanh.gialai.gov.vn', 'Từ Ngọc Vũ', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8418, 7704, 'Chuyên viên', 'nhathtm@vinhthanh.gialai.gov.vn', 'Hồ Thị Minh Nhật', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8420, 7704, 'Chuyên viên', 'nhinty@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Yến Nhi', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8422, 7778, 'Giám đốc', 'sinhlh@vinhthanh.gialai.gov.vn', 'Lê Hàn Sinh', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8424, 7778, 'Phó giám đốc', 'hongnv@vinhthanh.gialai.gov.vn', 'Nguyễn Văn Hồng', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8426, 7778, 'Chuyên viên', 'thaodtt@vinhthanh.gialai.gov.vn', 'Đặng Thị Thanh Thảo', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8427, 7704, 'Phó giám đốc', 'dungbx@vinhthanh.gialai.gov.vn', 'Bùi Xuân Dũng', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8475, 289, 'Chuyên viên', 'khanhnq@vinhthanh.gialai.gov.vn', 'Nguyễn Quốc Khánh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (8500, 280, 'Phó Chánh Văn phòng', 'lelt@vinhthanh.gialai.gov.vn', 'Lê Thị Lệ', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37667, 37589, 'Chủ tịch', 'drind@vinhthanh.gialai.gov.vn', 'Đinh DRin', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37685, 37589, 'Phó chủ tịch', 'vanvtt@vinhthanh.gialai.gov.vn', 'Võ Thị Thúy Vân', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37714, 37589, 'Trưởng Ban Kinh tế - Ngân Sách', 'khanhd@vinhthanh.gialai.gov.vn', 'Đinh Khánh', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37886, 37589, 'Trưởng Ban Văn hóa - Xã hội', 'tieud@vinhthanh.gialai.gov.vn', 'Đinh Tiêu', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37909, 37589, 'Phó Trưởng Ban KT-NS', 'canhtt@vinhthanh.gialai.gov.vn', 'Trần Thị Cảnh', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (37919, 37589, 'Phó Trưởng Ban VH-XH', 'thanhdt@vinhthanh.gialai.gov.vn', 'Đinh Trọng Thành', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (38060, 38056, 'Chỉ huy trưởng', 'ductt@vinhthanh.gialai.gov.vn', 'Trần Thanh Đức', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (38073, 38056, 'Phó', 'diennh@vinhthanh.gialai.gov.vn', 'Nguyễn Hồng Diện', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (38104, 38056, 'Trợ lý', 'huytn@vinhthanh.gialai.gov.vn', 'Trần Ngọc Huy', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (59829, 286, 'Chuyên viên', 'congnph@vinhthanh.gialai.gov.vn', 'Nguyễn Phi Công', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (71447, 71446, 'Văn thư', 'vanthucax@vinhthanh.gialai.gov.vn', 'Văn thư Công an xã', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112057, 7778, 'Chuyên viên', 'namdv@vinhthanh.gialai.gov.vn', 'Dương Văn Nam', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112059, 7778, 'Chuyên viên', 'nganlt@vinhthanh.gialai.gov.vn', 'Lục Thị Ngân', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112061, 7778, 'Chuyên viên', 'tuantha@vinhthanh.gialai.gov.vn', 'Trần Huỳnh Anh Tuấn', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112064, 7778, 'Chuyên viên', 'nghianh@vinhthanh.gialai.gov.vn', 'Nguyễn Hữu Nghĩa', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112066, 7778, 'Chuyên viên', 'damdg@vinhthanh.gialai.gov.vn', 'Đinh Giang Đam', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112068, 7778, 'Chuyên viên', 'minhtv@vinhthanh.gialai.gov.vn', 'Trần Văn Minh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112070, 7778, 'Chuyên viên', 'nguyenntn@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Ngọc Nguyên', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112072, 7778, 'Chuyên viên', 'supt@vinhthanh.gialai.gov.vn', 'Phan Thành Sự', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112074, 7778, 'Chuyên viên', 'hienntm@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Minh Hiền', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112076, 7778, 'Chuyên viên', 'minhbn@vinhthanh.gialai.gov.vn', 'Bùi Nguyệt Minh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112106, 7778, 'Chuyên viên', 'manlm@vinhthanh.gialai.gov.vn', 'Lê Minh Mẫn', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112108, 7778, 'Chuyên viên', 'anhv@vinhthanh.gialai.gov.vn', 'Huỳnh Văn An', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (112877, 7778, 'Chuyên viên', 'chaunh@vinhthanh.gialai.gov.vn', 'Nguyễn Hữu Châu', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (131941, 286, 'Chuyên viên', 'huytq@vinhthanh.gialai.gov.vn', 'Trần Quốc Huy', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (131965, 286, 'Chuyên viên', 'giangnth@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Hải Giang', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (242930, 242929, 'Văn Thư', 'vanthumnvt@vinhthanh.gialai.gov.vn', 'Trường Mầm Non Vĩnh Thạnh', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (243506, 242929, 'Hiệu trưởng', 'tranght@vinhthanh.gialai.gov.vn', 'Hà Thị Trang', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (243642, 243641, 'Văn thư', 'vanthumnvh@vinhthanh.gialai.gov.vn', 'Văn thư Mầm non Vĩnh Hảo', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244482, 243641, 'Hiệu trưởng', 'dieplt@vinhthanh.gialai.gov.vn', 'Lê Thị Diệp', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244485, 244484, 'Văn thư', 'vanthuthvt@vinhthanh.gialai.gov.vn', 'Văn thư trường Tiểu học Vĩnh Thạnh', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244487, 244484, 'Hiệu trưởng', 'trungtv@vinhthanh.gialai.gov.vn', 'Trần Văn Trung', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244490, 244489, 'Văn thư', 'vanthuthvh@vinhthanh.gialai.gov.vn', 'Văn thư trường Tiểu học Vĩnh Hảo', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244492, 244489, 'Hiệu trưởng', 'ngodv@vinhthanh.gialai.gov.vn', 'Đinh Văn Ngơ', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244495, 244494, 'Văn thư', 'vanthuthcsvt@vinhthanh.gialai.gov.vn', 'Văn thư trường THCS Vĩnh Thạnh', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (244522, 244521, 'Văn thư', 'vanthuthcsvh@vinhthanh.gialai.gov.vn', 'Văn thư trường THCS Vĩnh Hảo', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (245091, 244521, 'Hiệu trưởng', 'thientc@vinhthanh.gialai.gov.vn', 'Từ Chí Thiện', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (245112, 244494, 'Hiệu trưởng', 'cuongnv@vinhthanh.gialai.gov.vn', 'Nguyễn Văn Cượng', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (329981, 71446, 'Trưởng Công an xã', 'ngoandv@vinhthanh.gialai.gov.vn', 'Đinh Văn Ngoan', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (352390, 289, 'Chuyên viên', 'hanhnth@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Hồng Hạnh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (352401, 280, 'Chuyên viên', 'hoant@vinhthanh.gialai.gov.vn', 'Nguyễn Thị Hòa', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1148895, 283, 'Phó Giám đốc', 'thuongtv@vinhthanh.gialai.gov.vn', 'Trần Văn Thương', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1182358, 1271, 'Quản trị viên', 'admins@vinhthanh.gialai.gov.vn', 'Quản Trị Viên', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363880, 7704, 'Chuyên viên', 'vinhndvt@vinhthanh.gialai.gov.vn', 'Nguyễn Đình Vinh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363881, 7704, 'Chuyên viên', 'anhhhvt@vinhthanh.gialai.gov.vn', 'Huỳnh Hữu Ảnh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363882, 7704, 'Chuyên viên', 'hapvvt@vinhthanh.gialai.gov.vn', 'Phạm Văn Hà', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363883, 7704, 'Chuyên viên', 'phultkvt@vinhthanh.gialai.gov.vn', 'Lê Thị Kim Phú', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363884, 7704, 'Chuyên viên', 'oailtkvt@vinhthanh.gialai.gov.vn', 'Đinh Y Oai', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1363885, 7704, 'Chuyên viên', 'pinhllvt@vinhthanh.gialai.gov.vn', 'Lương Lê Pinh', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1564186, 1564185, 'Văn thư', 'vanthuubbc@vinhthanh.gialai.gov.vn', 'ủy ban bầu cử', 'alias', 'dept_administrator');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (1921184, 1920094, 'Trưởng trạm', 'tamnv@vinhthanh.gialai.gov.vn', 'Nguyễn Văn Tám', 'alias', 'leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2031757, 244484, 'Phó hiệu trưởng', 'bacnh@vinhthanh.gialai.gov.vn', 'Nguyễn Hoàng Bắc', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2057220, 244494, 'Phó hiệu trưởng', 'duochv@vinhthanh.gialai.gov.vn', 'Huỳnh Văn Được', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2060844, 244489, 'Phó hiệu trưởng', 'kydv@vinhthanh.gialai.gov.vn', 'Đào Văn Kỳ', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2078471, 243641, 'Phó hiệu trưởng', 'nuongdth@vinhthanh.gialai.gov.vn', 'Đoàn Thị Hồng Nương', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2078487, 244521, 'Phó hiệu trưởng', 'thanhlx@vinhthanh.gialai.gov.vn', 'Lê Xuân Thành', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (2080997, 242929, 'Phó hiệu trưởng', 'lytts@vinhthanh.gialai.gov.vn', 'Trần Thị Sao Ly', 'alias', 'unit_leader');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (3887910, 289, 'Chuyên viên', 'sondg@vinhthanh.gialai.gov.vn', 'Đinh Giang Sơn', 'alias', 'specialist');
INSERT INTO "person" ("id", "parent_id", "name", "refUname", "refFullname", "type", "rank") VALUES (4006938, 4006937, 'Văn thư', 'vanthuctd@vinhthanh.gialai.gov.vn', 'xã vĩnh thạnh', 'alias', 'dept_administrator');
